### ISSUE TITLE
Where is 'data/train_CWQ/te_idx.json'?

### ISSUE THREAD

**Issue by PaulZhang2718** [lanyunshi/Multi-hopComplexKBQA#7]
I have downloaded the data and pretrained-model you provided. But when I run ```./CWQ_Runner.sh``` to test, I got
```bash
successfully load Bert model ...
07/23/2020 01:00:46 - INFO - __main__ -   ***** Loading evaluation *****
07/23/2020 01:00:46 - INFO - __main__ -      Num dev examples = 3519
07/23/2020 01:00:46 - INFO - __main__ -      Num test examples = 3531
07/23/2020 01:00:46 - INFO - __main__ -      Batch size = 1
Traceback (most recent call last):
  File "code/KBQA_Runner.py", line 832, in <module>
    main()
  File "code/KBQA_Runner.py", line 627, in main
    te_idx = json.load(open('data/train_CWQ/te_idx.json', 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'data/train_CWQ/te_idx.json'
```

**Comment by lanyunshi** [comment]
Hi,

Please just kindly comment out the line. I use this line to debug but forget to remove it. I will correct this.

**Comment by PaulZhang2718** [comment]
Thanks. It works now.
